---
title: "Japan's Land Temperature Forecasting"
date: "May 2023"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(astsa)
library(tseries)
library(dplyr) 
library(ggplot2)
library(forecast)
library(imputeTS)
library(dynlm)
library(zoo)
library(xts)
```

1. Reading the data
```{r}
global_temp= read.csv("GlobalLandTemperaturesByCountry.csv")
global_temp_jpn = filter(global_temp, Country == "Japan")
```

2. Cleaning the data
```{r}
# Missing Values
print(paste0("The number of missing values are, ", sum(is.na(global_temp_jpn$AverageTemperature))))
tail(global_temp_jpn)
global_temp_jpn= global_temp_jpn[1:2072, ]

# Data Format
str(global_temp_jpn)
global_temp_jpn$date= as.Date(global_temp_jpn$dt, format = "%Y-%m-%d")
str(global_temp_jpn)


# Time Series Object
global_temp_jpn_ts= as.xts(x = global_temp_jpn[, c(-1, -4, -5)],
                           order.by = global_temp_jpn$date)
head(global_temp_jpn_ts)
```

```{r fig.height=5, fig.width=15}
plot(global_temp_jpn_ts$AverageTemperature[20:50], main= "Average Land Temperature of Japan")
```

3. Train Test Split
```{r}
n= dim(global_temp_jpn_ts)[1]
trn_n= floor(n*0.8)

train= global_temp_jpn_ts[1:trn_n, ]
dim(train)

test= global_temp_jpn_ts[(trn_n+1):n, ]
dim(test)
```
4. Analyzing TS data and Finding the best model and parameters
```{r}
acf2(train$AverageTemperature, 
     main= "ACF and PACF plots of Temperature before Seasonal Differencing (12)")
```

```{r}
# Differencing Data

diff= diff(global_temp_jpn_ts$AverageTemperature, 1)
acf2(diff, 
     main = "ACF and PACF plots of Temperature after Seasonal Differencing (1)")
```

```{r}
diff2= diff(global_temp_jpn_ts$AverageTemperature, 12)
acf2(diff2, 
     main = "ACF and PACF plots of Temperature after Seasonal Differencing (12)")
```

After analyzinf the above plot, the possible p, d, q and P, D, Q are
p= 1, 2
d= 0, 1
q= 0, 1, 2

P= 2, 3, 4
D= 0, 1
Q= 0, 1

S= 12

```{r}
p= c(1, 2)
d= c(0, 1)
q= c(0, 1, 2)

P= c(2, 3, 4)
D= c(0, 1)
Q= c(0, 1)

for (i in p){
  
  for (j in d){
    
    for (k in q){
      
      for (l in P){
        
        for (m in D){
          
          for (n in Q){
            
            tryCatch({
              
              print(paste(i, j, k, l, m , n, sep = ","))
              sarima(train$AverageTemperature, i, j, k, l, m, n, 12)
              
            }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
            
          }
          
        }
        
      }
      
    }
    
  }
  
}
```

After analyzing the above plots, the possible parameters are
- 211211
- 202411
- 202311
- 201211
- 200311
- 200211
- 102211
```{r}
sarima(train$AverageTemperature, 2, 1, 1, 2, 1, 1, 12)
sarima(train$AverageTemperature, 2, 0, 2, 4, 1, 1, 12)
sarima(train$AverageTemperature, 2, 0, 2, 3, 1, 1, 12)
sarima(train$AverageTemperature, 2, 0, 2, 4, 1, 1, 12)
sarima(train$AverageTemperature, 1, 0, 1, 2, 1, 0, 12)
```

```{r}
# After analyzing the above plots, the best combinations could be 2, 0, 2, 4, 1, 1 or 1, 0, 1, 2, 1, 0

tst_n= dim(test)
pred= sarima.for(train$AverageTemperature, n.ahead =tst_n, 2, 0, 2, 4, 1, 1, 12)
accuracy(object= pred$pred, test$AverageTemperature)

pred= sarima.for(train$AverageTemperature, n.ahead =tst_n, 1, 0, 1, 2, 1, 0, 12)
accuracy(object= pred$pred, test$AverageTemperature)
```

5. Forecast the next 5 months
```{r}
temperature= ts(global_temp_jpn_ts$AverageTemperature, 
                start= c(1841,1), end = c(2013, 08), frequency = 12)

forecast= sarima.for(temperature, n.ahead =5, 2, 0, 2, 4, 1, 1, 12)
```

